name: navatech_assignment
description: A Flutter app with infinite album/image scrolling, offline mode, caching, shimmer loading, animations, and DI.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^2.6.0
  equatable: ^2.0.7
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mockito: ^5.4.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/error.json